version: 0.2

phases:
#  install:
#    commands:
#      - apt-get update -y
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      # - echo "codebuild local test" > $CODEBUILD_SRC_DIR/output.txt
      - echo Run unit test
      - python3 test.py
artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - output.txt